### ISSUE TITLE
bug(base): `neorg` is no more a global variable. Change in upstream

### ISSUE THREAD

**Issue by snuffop** [pysan3/neorg-templates#9]
## Bug

Startup getting an error  unable to load module external.templates  ......module.lua:39: attempt to index global 'neorg' (a nil value)

## Reproduce

1. Pull the latest code from Neorg and neorg-templates

It looks like the breaking changes from neorg have caused the calls in this module to bork

05:39:29 PM msg_show "notes/journals/2023/08/02.norg" 22L, 460B written
   Error  05:39:29 PM notify.error [neorg] (17:39:29)
.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:438
Unable to load module external.templates - ...emplates/lua/neorg/modules/external/templates/module.lua:39: attempt to index global 'neorg' (a nil value)
   Warn  05:39:29 PM notify.warn [neorg] (17:39:29)
/home/marty/.local/share/nvim/lazy/neorg/lua/neorg.lua:95
Recovering from error...

**Comment by pysan3** [comment]
I can reproduce this. Thanks for reporting @snuffop!

Please wait till this weekend and I'll look into it.
